[book]
authors = ["Agent Learning Team"]
language = "zh-CN"
src = "src"
title = "从零开始学 Agent"
[build]
build-dir = "book"

[preprocessor.katex]

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = ""
additional-css = []
no-section-label = true


